### Introducción a numpy

convirtiendo una matriz a un array en numpy

In [23]:
import numpy as np

datos = [[1, 1, 150, 24],
         [2, 1, 160, 23],
         [3, 2, 170, 25],
         [4, 2, 165, 23],
         [5, 1, 160, 22]
        ]

print(datos)
datosnp = np.asarray(datos);
print(datosnp)

print(len(datosnp))
print(datosnp.shape) # dimensiones del array

print("algo parcial")
print(datosnp.shape[0])


#halando la media
print("procesando con numpy para la media")
print(np.mean(datosnp))
print(np.mean(datosnp, axis = None))
print(np.mean(datosnp, axis = 0))
print(np.mean(datosnp, axis = 1))

#hallando la mediana
print("procesando con numpy para la mediana")
print(np.median(datosnp))
print(np.median(datosnp, axis = None))
print(np.median(datosnp, axis = 0))
print(np.median(datosnp, axis = 1))



[[1, 1, 150, 24], [2, 1, 160, 23], [3, 2, 170, 25], [4, 2, 165, 23], [5, 1, 160, 22]]
[[  1   1 150  24]
 [  2   1 160  23]
 [  3   2 170  25]
 [  4   2 165  23]
 [  5   1 160  22]]
5
(5, 4)
algo parcial
5
procesando con numpy para la media
47.2
47.2
[  3.    1.4 161.   23.4]
[44.  46.5 50.  48.5 47. ]
procesando con numpy para la mediana
13.5
13.5
[  3.   1. 160.  23.]
[12.5 12.5 14.  13.5 13.5]


### Dar lectura a un archivo en python

Para esto se utilizará panda

In [28]:
import pandas as pd 
datitos = pd.read_csv("ejemplo.csv");
print(datitos)

  ID;EDAD;SEXO;ESTATURA
0     1;20;femenino;150
1    2;42;masculino;160
2     3;53;femenino;170
3    4;49;masculino;120
4     5;19;femenino;140
